//GET para obtener todas las producciones
GET http://localhost:3000/producciones

### Crear una nueva producción
POST http://localhost:3000/nuevaProduccion
Content-Type: application/json

{
  "titulo": "Nueva Producción",
  "categoria_id": 1,
  "resumen": "Descripción de la nueva producción.",
  "temporadas": 0,
  "duracion": "45 minutos",
  "trailer": "https://www.youtube.com/nuevo_trailer",
  "poster": "./posters/nuevo_poster.jpg",
  "generos": [1, 2],
  "reparto": [5, 6]
}

###
//Obtener una produccion por ID
GET http://localhost:3000/producciones/45
###

//Actualizar una produccion por ID
PUT  http://localhost:3000/updateProduccion/5
Content-Type: application/json

{
  "titulo": "Uwu Producción",
  "categoria_id": 1,
  "resumen": "Descripción de la nueva producción.",
  "temporadas": 3,
  "duracion": "45 minutos",
  "trailer": "https://www.youtube.com/nuevo_trailer",
  "poster": "./posters/nuevo_poster.jpg",
  "generos": [1, 2],
  "reparto": [3, 4]
}

###

//Eliminar una produccion
DELETE http://localhost:3000/deleteProduccion/15


###

//Filtrar por titulo
GET http://localhost:3000/producciones/filtrar/titulo?titulo=Guason

###

//Filtraro por genero
GET http://localhost:3000/producciones/filtrar/genero?genero_id=2

###

//Filtrar por categoria
GET http://localhost:3000/producciones/filtrar/categoria?categoria_id=1

